name       : knotifications
version    : 5.96.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/knotifications-5.96.0.tar.xz : 12933ae33e511b6a37fb3b0dc896248ffdd2ef007e2fc4dd05757fc8a8c7cb85
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-r-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(dbusmenu-qt5)
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
