name       : knotifications
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/knotifications-5.35.0.tar.xz : 2fa2801fa5f43602d6a6d389fb80688c49f4d79060d071a2c8929de088d2f622
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(phonon4qt5)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
    - libdbusmenu-qt-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
