name       : knotifications
version    : 5.57.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/knotifications-5.57.0.tar.xz : 7de068f4cf9bcefef54ae1cb180e2c0af9be951afbcaa960245507259620cf15
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
    - libdbusmenu-qt-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
