name       : knotifications
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/knotifications-5.38.0.tar.xz : ed7d33414840c8b25ce0f7fc446516bd85458b4e349825da026eb511a1d875cb
license    :
    - LGPL-2.1
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(phonon4qt5)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
    - libdbusmenu-qt-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
