name       : knotifications
version    : 5.69.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/knotifications-5.69.0.tar.xz : d449673969123f72d891498f39461a6b25d69ff8b64911c4179d7ca48d229e15
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
    - libdbusmenu-qt-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
