name       : knotifications
version    : 5.65.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/knotifications-5.65.0.tar.xz : 9d766c1566ea7cab83e6cd9c57f76583b3404f9864ed1ba1bc65535ea4c98087
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
    - libdbusmenu-qt-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
