name       : knotifications
version    : 5.92.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/knotifications-5.92.0.tar.xz : 8c4e095e3d96140f19e9f2e2dbc74df174e29416455671fc6680828038ea94b7
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-r-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(dbusmenu-qt5)
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
