name       : knotifications
version    : 5.32.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.32/knotifications-5.32.0.tar.xz : 9e0caf8599093e7c23bf0baa5f95d776f864a85f4d419bf14dc45fc1503d5719
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(phonon4qt5)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
