name       : knotifications
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/knotifications-5.25.0.tar.xz : b7810e42938331cd5f7f9f358362b3eb1221186c62762cd28860fdb66b6665bf
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(phonon4qt5)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
