name       : knotifications
version    : 5.93.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/knotifications-5.93.0.tar.xz : fe191b1fe55881d7e212a3b70fe08d53e47c32793d38f5d5a4d82b796796da4b
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-r-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(dbusmenu-qt5)
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
