name       : knotifications
version    : 5.53.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/knotifications-5.53.0.tar.xz : df9ef2b24f768bfced82a94af0756edc215b93dbe580411f4ab99ac910797239
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
    - libdbusmenu-qt-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
