name       : knotifications
version    : 5.77.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/knotifications-5.77.0.tar.xz : f288fe163a9297011af9f2d147e6516f07c1ed68ff0546cc0cf65e858bb40265
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-r-later
    - LGPL-2.1-only
component  : desktop.library
optimize   : lto
summary    : Desktop notifications.
description: |
    Desktop notifications.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
    - libdbusmenu-qt-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
