name       : knotifications
version    : 5.99.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/knotifications-5.99.0.tar.xz : 36b1126801f649b26fb77889a35874519e3f7033faa55cff20e965581c5c302b
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-r-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(dbusmenu-qt5)
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
